--Q1. What is the total revenue generated by male vs. female customers?
SELECT
	GENDER,
	SUM(PURCHASE_AMOUNT) AS REVENUE
FROM
	CUSTOMER
GROUP BY
	GENDER;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
	CUSTOMER_ID,
	PURCHASE_AMOUNT
FROM
	CUSTOMER
WHERE
	DISCOUNT_APPLIED = 'Yes'
	AND PURCHASE_AMOUNT >= (
		SELECT
			AVG(PURCHASE_AMOUNT)
		FROM
			CUSTOMER
	);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT
	ITEM_PURCHASED,
	ROUND(AVG(REVIEW_RATING)::NUMERIC, 2) AS AVERAGE_REVIEW_RATING
FROM
	CUSTOMER
GROUP BY
	ITEM_PURCHASED
ORDER BY
	AVERAGE_REVIEW_RATING DESC
LIMIT
	5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT
	SHIPPING_TYPE,
	ROUND(AVG(PURCHASE_AMOUNT), 2)
FROM
	CUSTOMER
WHERE
	SHIPPING_TYPE IN ('Standard', 'Express')
GROUP BY
	SHIPPING_TYPE;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT
	SUBSCRIPTION_STATUS,
	COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS,
	ROUND(AVG(PURCHASE_AMOUNT), 2) AS AVG_SPEND,
	ROUND(SUM(PURCHASE_AMOUNT), 2) AS TOTAL_REVENUE
FROM
	CUSTOMER
GROUP BY
	SUBSCRIPTION_STATUS
ORDER BY
	TOTAL_REVENUE,
	AVG_SPEND DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
	ITEM_PURCHASED,
	ROUND(
		100.0 * SUM(
			CASE
				WHEN DISCOUNT_APPLIED = 'Yes' THEN 1
				ELSE 0
			END
		) / COUNT(*),
		2
	) AS DISCOUNT_RATE
FROM
	CUSTOMER
GROUP BY
	ITEM_PURCHASED
ORDER BY
	DISCOUNT_RATE DESC
LIMIT
	5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH
	CUSTOMER_TYPE AS (
		SELECT
			CUSTOMER_ID,
			PREVIOUS_PURCHASES,
			CASE
				WHEN PREVIOUS_PURCHASES = 1 THEN 'New'
				WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10  THEN 'Returning'
				ELSE 'Loyal'
			END AS CUSTOMER_SEGMENT
		FROM
			CUSTOMER
	)
SELECT
	CUSTOMER_SEGMENT,
	COUNT(*) AS "Number of Customers"
FROM
	CUSTOMER_TYPE
GROUP BY
	CUSTOMER_SEGMENT;

--Q8. What are the top 3 most purchased products within each category? 
WITH
	ITEM_COUNTS AS (
		SELECT
			CATEGORY,
			ITEM_PURCHASED,
			COUNT(CUSTOMER_ID) AS TOTAL_ORDERS,
			ROW_NUMBER() OVER (
				PARTITION BY
					CATEGORY
				ORDER BY
					COUNT(CUSTOMER_ID) DESC
			) AS ITEM_RANK
		FROM
			CUSTOMER
		GROUP BY
			CATEGORY,
			ITEM_PURCHASED
	)
SELECT
	ITEM_RANK,
	CATEGORY,
	ITEM_PURCHASED,
	TOTAL_ORDERS
FROM
	ITEM_COUNTS
WHERE
	ITEM_RANK <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
	SUBSCRIPTION_STATUS,
	COUNT(CUSTOMER_ID) AS REPEAT_BUYERS
FROM
	CUSTOMER
WHERE
	PREVIOUS_PURCHASES > 5
GROUP BY
	SUBSCRIPTION_STATUS;

--Q10. What is the revenue contribution of each age group? 
SELECT
	AGE_GROUP,
	SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM
	CUSTOMER
GROUP BY
	AGE_GROUP
ORDER BY
	TOTAL_REVENUE DESC;


